# Generated by Django 5.0.1 on 2024-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatriz', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(max_length=17),
        ),
    ]
