# Generated by Django 5.0.1 on 2024-02-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatriz', '0004_alter_curso_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
