# Generated by Django 5.0.1 on 2024-02-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatriz', '0005_curso_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='AppMatriz/assets/horario')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
