# Generated by Django 5.0.1 on 2024-02-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatriz', '0006_horario_delete_curso_delete_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='nombre',
            field=models.CharField(default='no_name', max_length=40),
        ),
    ]
