# Generated by Django 5.0.1 on 2024-03-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatriz', '0007_horario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='imagen',
            field=models.ImageField(upload_to='horarios'),
        ),
    ]
