# Generated by Django 5.0.1 on 2024-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatriz', '0008_alter_horario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='horarios'),
        ),
    ]
